name: Build on push
# This workflow is triggered on pushes to the repository.
on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - uses: LucaFeger/action-maven-cli@master
      with:
        args: clean package
  
