name: Build on push
# This workflow is triggered on pushes to the repository.
on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - uses: xlui/action-maven-cli/jdk11@master"
      with:
        args: clean package
  
